### ISSUE TITLE
Unlinked Array Class

### ISSUE THREAD

**Issue by ConorOBrien-Foxx** [cheddar-lang/Cheddar#15]
**Version:** 0.1.2

### Problem

Arrays do not display properly.

### Desired Behavior

For arrays to display properly.

### How to Reproduce

Type `[1, 2, 3]` into the repl. Here's what is yielded:
```
cheddar> [1, 2, 3]
Symbol(UNLINKED_CLASS)
```

(Related: arrays don't print anything. E.g., `print([1, 2, 3])` doesn't give any output.

**Comment by vihanb** [comment]
Uh oh, that's not supposed to happen. I think I've already got a fix for this ready. But this should of passed the tests if this errored.... I'll have to investigate

**Comment by vihanb** [comment]
Hm, the tests pass. Didn't you clone from the @develop brach? That might be it...

**Comment by ConorOBrien-Foxx** [comment]
I did.

**Comment by vihanb** [comment]
okay, then that's it

**Comment by vihanb** [comment]
Closing as this is not reproducible on master
