### ISSUE TITLE
String representations lacking escapes

### ISSUE THREAD

**Issue by Sp3000** [cheddar-lang/Cheddar#22]
**Version:** 0.3.0

### Problem

```
cheddar> "\""
 """
```

### Desired Behavior

Ideally, the output string representation should be such that it produces the original string (e.g. `'"'` or `"\""` in this case).

**Comment by vihanb** [comment]
I think I'll just override the `repr` operator on the string class rather than make this REPL-specific

**Comment by vihanb** [comment]
Added in 3b53b988ed8b15c7bba3c672c317736dc36a6482
