### ISSUE TITLE
I can't enter a nil

### ISSUE THREAD

**Issue by Maltysen** [cheddar-lang/Cheddar#24]
when I type `nil` it says that `nil` is an undefined variable.

**Comment by vihanb** [comment]
there is no nil type so idk whether this is a proposal or an invalid bug report :|

**Comment by Maltysen** [comment]
but the array part of your doc says there is

**Comment by Maltysen** [comment]
`[1,, 3] // [1, nil, 3]`

**Comment by vihanb** [comment]
Oh, that's outdated. I should remove it >_>

**Comment by Maltysen** [comment]
so, yeah then, you can make this a proposal too

**Comment by Maltysen** [comment]
you should prolly have some `null` type

**Comment by vihanb** [comment]
@
