### ISSUE TITLE
Weirdness with comparisons

### ISSUE THREAD

**Issue by Maltysen** [cheddar-lang/Cheddar#28]
This goes even further than the asymmetricalness already mentioned:

`true>2` gives that weird message mentioned in that issue about the aysmmetricalness, but `2>true` gives `> has no behavior for types nil and Boolean`.

why is `2` a type `nil`? this was another reason why i initially though there was a `nil` type.

**Comment by vihanb** [comment]
Oh, I know exactly why this is happening. I already have a fix made and on GH but it's not merged

**Comment by vihanb** [comment]
Fixed in 7e1aacd3472789559b31dd866753ea792a4521e0
