### ISSUE TITLE
Where is xor

### ISSUE THREAD

**Issue by Maltysen** [cheddar-lang/Cheddar#29]
`^` is doing exponentiation for some reason, can't find xor

**Comment by vihanb** [comment]
It's `xor`

**Comment by vihanb** [comment]
idk if I even implemented it though I probably forgot

**Comment by vihanb** [comment]
aaand I forgot

**Comment by vihanb** [comment]
Fixed in 8bfede3498ecbcdaa30ff9327132445704a59204
