### ISSUE TITLE
Can't type Infinity or NaN

### ISSUE THREAD

**Issue by Maltysen** [cheddar-lang/Cheddar#32]
I can make `Infinity` with `1/0` and `NaN` with `0/0` or `1/0 - 1/0`, because internally you're using js numbers, but unlike js, `Infinity` and `NaN` are being treated like identifiers, so I can't type them as literals.

**Comment by vihanb** [comment]
This is a different bug... there should be no infinite or NaN. It's because I'm using JS numbers internally which is the problem >_<
