### ISSUE TITLE
I can redefine constants

### ISSUE THREAD

**Issue by Maltysen** [cheddar-lang/Cheddar#40]
```
cheddar> const c=7
cheddar> c
 7
cheddar> c=5
 5
cheddar> c
 5
```

**Comment by vihanb** [comment]
This isn't really a bug, more of "Downgoat didn't give a shit and forgot to do it and now downgoat is sad because they are so many bugs ;_;" ;_;

**Comment by vihanb** [comment]
Fixed: dcdde65708d0c61205c905ae7bea23d0503240b5

**Comment by Maltysen** [comment]
is the repo not updated? cuz this still happens there.

**Comment by vihanb** [comment]
As I said in chat the REPL follows the release branch which will not update until the next pre release.
