### ISSUE TITLE
Escape sequences and characters

### ISSUE THREAD

**Issue by ConorOBrien-Foxx** [cheddar-lang/Cheddar#44]
Which escape code should there be? Obviously `\n` for newline and `\t` for tab, but what else? Surely we shouldn't have the archaic vertical tab `\v`. Should Unicode escapes be `\uXXXX`? What should escaping characters with no associated escape could do? What should escaping a number do?

**Comment by Maltysen** [comment]
idk about the others, but traditionally, escaping something that can't be escaped leaves the backslash in there as a literal `\`

**Comment by vihanb** [comment]
This is a feature-request unless you formally outline the specification and implementation of your proposal

**Comment by ConorOBrien-Foxx** [comment]
It _is_ a feature-request.

**Comment by vihanb** [comment]
then why did you do proposal:

**Comment by Maltysen** [comment]
what's the difference?

**Comment by ConorOBrien-Foxx** [comment]
Same diff?

**Comment by phase** [comment]
Proposal signifies that you already have an outline on how it should work.

**Comment by ConorOBrien-Foxx** [comment]
Oh, okay. Thanks @phase. @vihan, you should probably mention that on the issue proposal thingy
