### ISSUE TITLE
REPL has horizontal overflow

### ISSUE THREAD

**Issue by Maltysen** [cheddar-lang/Cheddar#47]
There is a little horizontal scrolling on the REPL, i'm guessing you didn't account for padding on the body, etc.

**Comment by vihanb** [comment]
Open online REPL issues on the website repo. not the Cheddar repo

**Comment by vihanb** [comment]
link: https://github.com/cheddar-lang/cheddar-lang.github.io

**Comment by Maltysen** [comment]
where is that?
