### ISSUE TITLE
Weirdness with range to -infinity

### ISSUE THREAD

**Issue by Maltysen** [cheddar-lang/Cheddar#51]
```
cheddar> 4:(1/0)
 Invalid array length
cheddar> 4:(-1/0)
 Cannot read property 'constructor' of undefined
cheddar> 4:-1000
 [4, 3, 2, 1, 0, -1, -2, -3, -4, -5, -6, -7, -8, -9, ...

```

Array till `Infinity` works, giving invalid length, but till `-Infinity` gives some weird error, even though normally, ranges till negatives work.

**Comment by vihanb** [comment]
Again what's the desired behavior?

**Comment by Maltysen** [comment]
Raise the same `Invalid Length` error.

**Comment by vihanb** [comment]
dividing by zero is a separate bug so i'm closing this
