### ISSUE TITLE
Ranges with float args borked

### ISSUE THREAD

**Issue by Maltysen** [cheddar-lang/Cheddar#52]
```
cheddar> 4:.5
 [3.5, 2.5, 1.5, 0.5]
cheddar> 4:.001
 [3.001, 2.001, 1.001, 0.001]
cheddar> .1:5
 [0.1, 1.1, 2.1, 3.1, 4.1]
cheddar> .1:5.1
 [0.1, 1.1, 2.1, 3.1, 4.1]
cheddar> .1:5.2
 [0.1, 1.1, 2.1, 3.1, 4.1]
cheddar> .1:6
 [0.1, 1.1, 2.1, 3.1, 4.1, 5.1]
cheddar> .1:5.5
 [0.1, 1.1, 2.1, 3.1, 4.1]
```

I'm not gonna try and interpret what just happened there...

**Comment by vihanb** [comment]
@cyoce this is your range function pls fix (its very fast tohugh 10/10)

**Comment by vihanb** [comment]
What is the desired behavior? I don't know what it's supposed to be (which is why I have the template pls use)

**Comment by ConorOBrien-Foxx** [comment]
I designed it with this behaviour.

**Comment by ConorOBrien-Foxx** [comment]
Tho it could use some fixing

**Comment by Maltysen** [comment]
well for example, just picking the `1:5.2`, that should at least go up to, `5.1`, it is not. i'm not sure what the behavior should be, you have to decide that for yourself, this is wrong for sure tho.

**Comment by ConorOBrien-Foxx** [comment]
yeah, definitely. will research another technique

**Comment by ConorOBrien-Foxx** [comment]
Will work on it today or tomorrow.

**Comment by vihanb** [comment]
@ConorOBrien-Foxx don't mean to nag you but is it tomrrow yet? :P

**Comment by ConorOBrien-Foxx** [comment]
@vihanb  I don't mean to sound ticked but I can't reliably commit on windows because y'all keep making me reinstall....

**Comment by cyoce** [comment]
This function was not intended for float values... Outline a desired
behavior and I could fix it

**Comment by vihanb** [comment]
@ConorOBrien-Foxx sorry >_> though perhaps just branch of `develop` and make a PR where conflicts can be resolved:

```
$ git checkout -b fix-float-ranges develop
$ <make changes>
$ git commit -a
$ git push
```

then just PR from the web

**Comment by ConorOBrien-Foxx** [comment]
I'm not good with git, but I'll try.

**Comment by ConorOBrien-Foxx** [comment]
In the process of fixing the issue.
