### ISSUE TITLE
Mocha errors do not show

### ISSUE THREAD

**Issue by vihanb** [cheddar-lang/Cheddar#54]
On the Mocha tests, when an errors occurs, an obtrusive error shows:

```
YOU MESSED UP! THE RESULT IS "<result>" AND THE DESIRED RESULT WAS "<desired result"
```

This error was very helpful and made me feel so bad about the error, I then had to fix it so I would stop feeling bad. This is very critical

**Comment by The-Quill** [comment]
Is this on Master or release-1.0.0

**Comment by vihanb** [comment]
release-1.0.0

**Comment by schas002** [comment]
> **vihanb** added the [bug] label 5 hours ago

kek

**Comment by vihanb** [comment]
Was this fixed? I think it was fixed. @The-Quill
