### ISSUE TITLE
Cheddar hates the letters "t", "q", and "r", but only lowercase

### ISSUE THREAD

**Issue by Maltysen** [cheddar-lang/Cheddar#55]
```
cheddar> var t = 6
cheddar> t
 Attempted to access undefined variable `t`
cheddar> var a = 9
cheddar> a
 9
cheddar> var T = 8
cheddar> T
 8
cheddar> var q = 4
cheddar> q
 Attempted to access undefined variable `q`
cheddar> var Q = 3
cheddar> Q
 3
cheddar> var r = 10
cheddar> r
 Attempted to access undefined variable `r`
cheddar> var R = 17
cheddar> R
 17
cheddar> var w = 10
cheddar> w
 10
```

![image](https://cloud.githubusercontent.com/assets/10355450/16469608/fbaea4b6-3e1f-11e6-945d-47034ba58b18.png)

**Comment by Maltysen** [comment]
This happens for `const` also.

**Comment by vihanb** [comment]
@Maltysen `const` is because it's a reserved keyword but it should throw an error. this is very weird behavior

**Comment by Maltysen** [comment]
@vihanb no i mean `const t = 9` also does the same thing

**Comment by Maltysen** [comment]
```
cheddar> var const = 6
cheddar> const
 6
```

@vihanb on the other hand ^ works

**Comment by Maltysen** [comment]
also

```
cheddar> var const = 6
cheddar> const
 6
```

**Comment by vihanb** [comment]
wtf

**Comment by Maltysen** [comment]
@vihanb I already described this in:
https://github.com/cheddar-lang/Cheddar/issues/41

**Comment by vihanb** [comment]
goddamit. I don't give enough shits to fix this. you know what f*ck whoever uses those variables, i dont care enough

**Comment by The-Quill** [comment]
many tears were shed for @vihanb's lost shits

**Comment by vihanb** [comment]
;_;

**Comment by vihanb** [comment]
@ches y u do dis
