### ISSUE TITLE
STDLIB Roadmap - v1.0.0

### ISSUE THREAD

**Issue by vihanb** [cheddar-lang/Cheddar#56]
Target items to ship by v1.0.0 in the standard library.

### Math
 - [x] E
 - [x] PI
 - [x] PHI
 - [x] MILL
 - [x] GAMMA
 - [x] AVOGADRO
 - [x] fib
 - [x] isprime
 - [ ] factor

### String
 - [x] letters
 - [x] digits
 - [x] alphanumeric
 - [x] split
 - [x] slice
 - [x] ord
 - [x] len
 - [x] rev
 - [x] chars
 - [x] count
 - [ ] locate
 - [ ] locateLast
 - [x] replace
 - [ ] replaceAll
 - [ ] has

### Array
 - [ ] slice
 - [x] len
 - [x] rev
 - [ ] count
 - [ ] locate
 - [ ] locateLast
 - [ ] has

### Crypto
 - [ ] SHA1
 - [ ] SHA3

### http
 - [ ] get
 - [ ] post
 - [ ] put
 - [ ] delete
 - [ ] request
 - [ ] exists

### IO
 - [x] printf
 - [x] sprintf
 - [x] prompt

### stream
 - [ ] read
 - [ ] write
 - [ ] exists

### Encoding
 - [x] UTF8
 - [ ] UTF16
 - [ ] LATIN1

**Comment by schas002** [comment]
Why close this issue?

**Comment by vihanb** [comment]
@schas002 it's not really an issue. more of a todo list. I'll split it up into more things
