### ISSUE TITLE
atan is broken

### ISSUE THREAD

**Issue by The-Quill** [cheddar-lang/Cheddar#7]
**Version:** 0.1 alpha

### Problem

`atan` is broken.

On line 224 of `interpreter/core/primitives/op/number.es6`, `'asin'` should be `'atan'`.

### Desired Behavior

For it to work

### How to Reproduce

 1. Read the code
 2. ...
 3. profit!

**Comment by vihanb** [comment]
What error does it throw?

**Comment by The-Quill** [comment]
It doesn't throw an error, you have double defined `asin`, so I guess, no op or something:

```
cheddar> atan 3
T_REPL:ERROR - `atan` has no behavior for types `nil` and `Number`
```

**Comment by vihanb** [comment]
Ah ok will fix

**Comment by The-Quill** [comment]
:D
