### ISSUE TITLE
cleanup is extremely dangerous

### ISSUE THREAD

**Issue by ararslan** [cheddar-lang/Cheddar#75]
Running `bin/cleanup` can (and in my case has) done bad things. In particular, there are two things very wrong with this line:
```bash
sudo rm -rf "$1/bin/"
```

First, without passing a command line argument to the script, `$1` is blank. That means you're forcibly recursively removing the root folder `/bin` where nearly all system command line utilities are stored.

Second, `sudo`. Do *not*. If users want to run the script as root, that's their prerogative, but it certainly should not be the default within the script.

Apologies If I sound a little salty, but I'm currently reinstalling my operating system in hopes of getting `/bin` back...

**Comment by vihanb** [comment]
very very very very very very sorry about your OS >_> will once i get out of class

**Comment by vihanb** [comment]
Fixed in ae1e1ca366f274f812945aba3526d05415b93e6f
