### ISSUE TITLE
Proposal: Special Variables

### ISSUE THREAD

**Issue by somebody1234** [cheddar-lang/Cheddar#79]
# Overview

Self explanatory.
# Definition

All start with a reserved character (say `$`). A list is below.

`$` for arguments
`$$` for parent arguments (etc.)
`$1` for first argument (etc.)
`$_` for loop variable
`$_1` for first loop variable (etc.)
`$__` for loop variables

There could possibly be a chance for special-argument lambdas, with syntax to make it obvious and easy to parse. (e.g. a lambda would be `$1+$2`)

Feel free to edit/suggest more special variables.

**Comment by ConorOBrien-Foxx** [comment]
Two for loop arguments?

**Comment by somebody1234** [comment]
@ConorOBrien-Foxx ?

**Comment by ConorOBrien-Foxx** [comment]
@somebody1234  `$_` and `$__`?

**Comment by somebody1234** [comment]
@ConorOBrienFoxx Yeah, the second one returns e.g. `[i, j]` in `for(var i := 0, j := 0; i++, j++; i < 10) { Foo(); }`

**Comment by ConorOBrien-Foxx** [comment]
What would the point of that loop be? if `i == j`?

**Comment by somebody1234** [comment]
@ConorOBrien-Foxx None, it's just an example

**Comment by ConorOBrien-Foxx** [comment]
@somebody1234 so variables defined in a for loop are stored in `$_`, `$__`...?

**Comment by somebody1234** [comment]
@ConorOBrien-Foxx `$_` and `$_1` would be `i`, `$_2` would be j, `$__` would be `[i, j]`
