### ISSUE TITLE
Proposal: Things to change

### ISSUE THREAD

**Issue by somebody1234** [cheddar-lang/Cheddar#80]
# Definition
Change lambda to `=>` to follow JS/C# (instead of Java)
Change functionized operator syntax - the current syntax does not really fit

**Comment by vihanb** [comment]
The thing with arrow functions is that they are only => in C# and JS ES6. C++, Java (possibly the two most popular languages) all use ->

**Comment by vihanb** [comment]
Haskell uses same functional op syntax so I don't think that's s a big problem
