### ISSUE TITLE
0 == 0 -> false

### ISSUE THREAD

**Issue by quartata** [cheddar-lang/Cheddar#81]
**Version:** v1.0.0-beta.50

### Problem

`==` does not work properly for `0` and `0`.

    cheddar> 0 == 0
    false
    cheddar> 1 == 1
    true

### Desired Behavior

Comparing two literals or lvalues that are both `0` should yield `true`.

### How to Reproduce

 1. Simply compare two zeros.

**Comment by vihanb** [comment]
Fixed in 9d2df293ed6d502bccc57da194d752eec22f157c

**Comment by ConorOBrien-Foxx** [comment]
uh oh. is it borked again?

**Comment by vihanb** [comment]
@ConorOBrien-Foxx it was never fixed but I know exactly what the problem is, I just need to fix it
