### ISSUE TITLE
Feature request: Pytek-style chaining syntax

### ISSUE THREAD

**Issue by somebody1234** [cheddar-lang/Cheddar#83]
# Definition

`~>` feeds variables as arguments for chain
`:>` or something continues chain, tuples of functions can be used if the next argument accepts multiple arguments

**Comment by vihanb** [comment]
Could you clarify what a chain is? I have no idea what it is (maybe add overview & examples too :3)

**Comment by somebody1234** [comment]
[Pytek docs here](http://pytek.starmaninnovations.com/docs/syntax),  gives the example:

    \foo( \bar( \baz(x), \baq(y) ), \faz(z) )

is equivalent to:

    x, y, z ~> \baz, \baq :> \bar, \faz :> \foo

**Comment by ConorOBrien-Foxx** [comment]
Doesn't this assume fixed arity of functions? And how would this look in cheddar?

**Comment by somebody1234** [comment]
@ConorOBrien-Foxx Oh yeah, I'm thinking chain resolution would happen at the same time as overload resolution though, and that's how it looks in Cheddar, Pytek uses `->` instead of `:>`, but both `->` and `=>` are taken in Cheddar

**Comment by vihanb** [comment]
this seems like interesting idea but i sitll have no idea wat a chain is ._.

**Comment by somebody1234** [comment]
@vihanb Compare the two, basically it makes nested calls e.g. `a(b(c(d(foo))))` way neater

**Comment by ConorOBrien-Foxx** [comment]
@somebody1234 How would a "tuple of functions" look in cheddar?

**Comment by somebody1234** [comment]
@ConorOBrien-Foxx Just `(functionOne, functionTwo)` (e.g. `foo(f1(x), f2(y, z))` becomes `x, y, z ~> f1, f2 :> foo`, IDK if parens should be mandatory

**Comment by ConorOBrien-Foxx** [comment]
@somebody1234  but cheddar doesn't have tuples.

**Comment by somebody1234** [comment]
@ConorOBrien-Foxx 1. Not yet, but it's on `cheddar.vihan.org`, 2. They're not actually tuples, more a syntax construct that looks liek tuples
