### ISSUE TITLE
Comments are broken

### ISSUE THREAD

**Issue by tuxcrafting** [cheddar-lang/Cheddar#85]
**Version:** v1.0.0-beta.36

### Problem

COMMENTS ARE BROKEN

### Desired Behavior

Ignore comments

### How to Reproduce

```
cheddar> // lolwut
Syntax Error: Unexpected token at 1:3
1 | // lolwut
  |    ^
cheddar> /* bro */
Runtime Error: Invalid regular expression: /* bro */: Nothing to repeat
cheddar> # hmmm... wat
Syntax Error: Unexpected token at 1:0
1 | # hmmm... wat
  | ^
```

**Comment by schas002** [comment]
**Problem** might be a bit clearer.

**Comment by schas002** [comment]
I see that the `//` actually gets parsed as an empty regex, `/* */` as an invalid regex, and `#` not even parsed normally, saying it's an "Unexpected token".

**Comment by tuxcrafting** [comment]
@schas002 **Problem** is pretty clear IMO :P

**Comment by vihanb** [comment]
# comments are no more and schas is spot on with the fact they're being parsed as regexes

**Comment by schas002** [comment]
Why did comments disappear?

**Comment by tuxcrafting** [comment]
@vihanb lolwut why comments are no more

**Comment by vihanb** [comment]
@tuxcrafting @schas002 it was stupid `#` creating heading. I meant `#` comments are no moree

**Comment by vihanb** [comment]
@tuxcrafting btw: pls update your cheddar. your version is very old

**Comment by tuxcrafting** [comment]
@vihanb I am up-to-date with the version on NPM

**Comment by schas002** [comment]
Then guess, the Node package is out of date. The latest version is on GitHub, version 1.0.0-beta.55.

**Comment by vihanb** [comment]
.55 is latest version npm. You must be updating incorrectly

**Comment by schas002** [comment]
Speaking of which, I should wake my Cheddar instance on C9 up, and update Cheddar in there asap.

**Comment by schas002** [comment]
@vihanb I see...
