### ISSUE TITLE
Add `Infinity` and `NaN` constants

### ISSUE THREAD

**Issue by tuxcrafting** [cheddar-lang/Cheddar#94]
It would be very convenient to have the `Infinity` and `NaN` constants in Cheddar, because the values exists, but the only way to get them is `1/0` and `0/0`

**Comment by tuxcrafting** [comment]
Fixed in https://github.com/cheddar-lang/Cheddar/commit/e2b5039c90dc28893891e4c274367aafce4b2f5b

**Comment by schas002** [comment]
@tuxcrafting and in https://github.com/cheddar-lang/Ches/commit/5603857ab68ab3638ff37b6fcc3a974de00ba748 of Ches, the versatile parser powering Cheddar.

**Comment by schas002** [comment]
> cheddar-lang/Ches @ 5603857

...
